main: net.tfminecraft.DenarEconomy.DenarEconomy
api-version: 1.20
name: DenarEconomy
version: ${project.version}
author: Drefvelin

depend: [MMOItems, MythicLib, TLibs]

commands:
  deco:
      useage: /<command>
      description: Economy Command
  pouch:
      useage: /<command>
      description: Pouch Command