main: net.tfminecraft.denareconomy.DenarEconomy
api-version: 1.20
name: DenarEconomy
version: ${project.version}
author: Drefvelin

depend: [MMOCore, MMOItems, MythicLib]

commands:
  deco:
      useage: /<command>
      description: Economy Command